name: Qodana
on:
  issues:
    types:
      - opened
  branch_protection_rule:
    types: [created, deleted]
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - master # The 'master' branch
      - 'releases/*' # The release branches
      - '*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Test
        run: |
          mkdir -p .qodana/code-coverage
          go test ./... --coverprofile .qodana/code-coverage/coverage.out

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-coverage-data.zip
          path: .qodana/code-coverage
          
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        if: always()
        with: 
          args: pr-mode, post-pr-comment
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
